version: "3.8"

services:
  web:
    build:
      dockerfile: "./Dockerfile"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: "mero_container"
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "mydb"
