version: "3.8"
name: "main_container_of_compose"

services:
  web:
    image: "mero_image_from_compose"
    container_name: "mero_node_container"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: "mero_db_container"
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "mydb"
